
name: Publish to Github Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: install misk-web
        run: |
          mkdir ~/.npm-global
          npm config set prefix '~/.npm-global'
          PATH=~/.npm-global/bin:$PATH
          npm install -g @misk/cli
      - name: build tabs
        run: miskweb ci-build -e
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Publish packages
        #if: github.repository == 'cashapp/misk'
        run: ./gradlew -x samples:exemplar:publish -x samples:exemplarchat:publish -Dorg.gradle.internal.publish.checksums.insecure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
